version: 2

updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "chore"
    labels:
      - dependencies
    open-pull-requests-limit: 5

  # Go modules (main)
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "chore"
    labels:
      - dependencies
    open-pull-requests-limit: 5
    groups:
      minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]

  # Go modules (generator)
  - package-ecosystem: "gomod"
    directory: "/cmd/genholidays"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "chore"
    labels:
      - dependencies
    open-pull-requests-limit: 5
    groups:
      minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
